# Generated by Django 4.2.26 on 2025-11-10 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('type', models.CharField(default='device', max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bandwidth_mbps', models.FloatField(blank=True, null=True)),
                ('latency_ms', models.FloatField(blank=True, null=True)),
                ('directed', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='topo.node')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='topo.node')),
            ],
        ),
        migrations.AddConstraint(
            model_name='edge',
            constraint=models.CheckConstraint(check=models.Q(('source', models.F('target')), _negated=True), name='no_self_loop'),
        ),
    ]
